---
title: "kaggle"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r cars,warnings=0}
library('dplyr')
library('reshape')
library(plotly)
library(RColorBrewer)
data1 <- read.csv('/Users/yimanzhang/Desktop/101-innovations-research-tools-survey/survey_cleaned.csv',header=1)
dim(data1)
names(data1)
levels(data1$PUBYEAR)
data1$PUBYEAR <- data1$PUBYEAR %>% 
    relevel(ref='before 1991') 
f <- function(x,y){
  new_data <- x %>%
    melt(id=c('ID', "PUBYEAR")) %>%
    filter(value!=''&PUBYEAR!='') %>%
    group_by(PUBYEAR,variable) %>%
    summarise(n=n()) 
  p <- plot_ly(new_data, x=new_data$PUBYEAR,y=new_data$n,
               color=new_data$variable, type='bar',
               colors=brewer.pal(y,"Paired")) %>%
    layout(barmode='stack')
  return(p)
  
}
data1=data1[data1$PUBYEAR!='',]
data1=droplevels(data1)


```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
f(select(data1, ID, PUBYEAR, PHYS:ARTHUM),y=8)
f(select(data1, ID, PUBYEAR, RTOOL:ANALYZOTHCL),y=9)
f(select(data1, ID, PUBYEAR, WORD:WRITESPECCL),y=9)
f(select(data1, ID, PUBYEAR, GITHUB:DATASPECCL),y=9)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
